# -*- coding: utf-8 -*-
"""Cópia de Tarefa2Controle(Luísa).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_9b12xlesCmL-lU9fqj3Xtf3I6ggrB4
"""

pip install control

"""Importação da biblioteca"""

import control.matlab as ctr

"""**Exercício 1:**"""

num1=[2]
den1=[1]
G1=ctr.tf(num1,den1)
print(G1)

num2=[4]
den2=[1,0]
G2=ctr.tf(num2,den2)
print(G2)

num3=[1]
den3=[1,0]
G3=ctr.tf(num3,den3)
print(G3)

"""**Bloco 1(soma):**

"""

Gsoma=G1+G2
print(Gsoma)

"""**Bloco 2(multiplicação):**"""

Gmulti=G3*Gsoma
print(Gmulti)

"""**Exercício 2:**"""

numEx2=[25]
denEx2=[1,6,25]
GEx2=ctr.tf(numEx2,denEx2)
print(GEx2)

"""**Importação Matplotlib**



"""

import matplotlib.pyplot as plt

"""**Analise:**"""

y,t=ctr.step(GEx2)

wn=5
z=0.6

F=ctr.tf([wn**2],[1,2*z*wn,wn**2])
y,t=ctr.step(F)

plt.plot(t,y)
plt.xlabel('Tempo, Segundos')
plt.ylabel('Saída $y(t)$')
plt.title('Resposta ao degrau unitário:')
plt.grid()
print(F)

ctr.damp(F)

ctr.stepinfo(F)

